import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "../styles/globals.css";

const roboto = Roboto({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: '--font-roboto',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: "W-conv",
	description: "Generated by create next app",
};

export default function RootLayout({
																		 children,
																	 }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en"
					suppressHydrationWarning
		>
		<body
			className={`${roboto.variable} antialiased`}
		>
		{children}
		</body>
		</html>
	);
}
