import { JobType } from './job-type.enum'

export const JobTypeCategories: Record<string, JobType[]> = {
  IMAGE: [
    JobType.JPG_TO_AVIF,
    JobType.JPG_TO_GIF,
    JobType.JPG_TO_PNG,
    JobType.JPG_TO_TIFF,
    JobType.JPG_TO_WEBP,
    JobType.PNG_TO_AVIF,
    JobType.PNG_TO_GIF,
    JobType.PNG_TO_JPG,
    JobType.PNG_TO_TIFF,
    JobType.PNG_TO_WEBP,
    JobType.TIFF_TO_JPG,
    JobType.TIFF_TO_PNG,
    JobType.TIFF_TO_WEBP,
    JobType.TIFF_TO_GIF,
    JobType.TIFF_TO_AVIF,
    JobType.GIF_TO_JPG,
    JobType.GIF_TO_PNG,
    JobType.GIF_TO_TIFF,
    JobType.GIF_TO_WEBP,
    JobType.GIF_TO_AVIF,
    JobType.WEBP_TO_JPG,
    JobType.WEBP_TO_PNG,
    JobType.WEBP_TO_TIFF,
    JobType.WEBP_TO_GIF,
    JobType.WEBP_TO_AVIF,
    JobType.AVIF_TO_JPG,
    JobType.AVIF_TO_PNG,
    JobType.AVIF_TO_TIFF,
    JobType.AVIF_TO_GIF,
    JobType.AVIF_TO_WEBP,
  ],
  DOCUMENT: [JobType.PDF_TO_DOCX],
  AUDIO: [
    JobType.MP3_TO_WAV,
    JobType.MP3_TO_FLAC,
    JobType.MP3_TO_OGG,
    JobType.MP3_TO_AAC,
    JobType.AAC_TO_MP3,
    JobType.AAC_TO_WAV,
    JobType.AAC_TO_FLAC,
    JobType.AAC_TO_OGG,
    JobType.WAV_TO_MP3,
    JobType.WAV_TO_AAC,
    JobType.WAV_TO_FLAC,
    JobType.WAV_TO_OGG,
    JobType.FLAC_TO_MP3,
    JobType.FLAC_TO_WAV,
    JobType.FLAC_TO_AAC,
    JobType.FLAC_TO_OGG,
    JobType.OGG_TO_MP3,
    JobType.OGG_TO_WAV,
    JobType.OGG_TO_AAC,
    JobType.OGG_TO_FLAC,
  ]
}

export type JobTypeCategory = keyof typeof JobTypeCategories
