import { MimeType } from '@/shared/constants/mimetype'

export const mimeDescriptions: Record<MimeType, string> = {
  [MimeType.JPEG]: '.jpg and .jpeg image files',
  [MimeType.PNG]: '.png image files',
  [MimeType.GIF]: '.gif image files',
  [MimeType.WEBP]: '.webp image files',
  [MimeType.SVG]: '.svg vector images',
  [MimeType.BMP]: '.bmp image files',
  [MimeType.TIFF]: '.tif and .tiff image files',
  [MimeType.ICON]: '.ico icon files',
  [MimeType.HEIC]: '.heic image files (iPhone photos)',

  [MimeType.MP3]: '.mp3 audio files',
  [MimeType.OGG_AUDIO]: '.ogg audio files',
  [MimeType.WAV]: '.wav audio files',
  [MimeType.WEBM_AUDIO]: '.webm audio files',
  [MimeType.AAC]: '.aac audio files',
  [MimeType.FLAC]: '.flac audio files',
  [MimeType.WMA]: '.wma audio files',

  [MimeType.MP4]: '.mp4 video files',
  [MimeType.WEBM_VIDEO]: '.webm video files',
  [MimeType.OGG_VIDEO]: '.ogv video files',
  [MimeType.AVI]: '.avi video files',
  [MimeType.MPEG]: '.mpeg and .mpg video files',
  [MimeType.MOV]: '.mov video files',
  [MimeType.MKV]: '.mkv video files',

  [MimeType.PLAIN]: '.txt plain text files',
  [MimeType.HTML]: '.html and .htm HTML files',
  [MimeType.CSS]: '.css stylesheet files',
  [MimeType.CSV]: '.csv comma-separated files',
  [MimeType.MARKDOWN]: '.md Markdown files',
  [MimeType.XML]: '.xml text files',

  [MimeType.JSON]: '.json files',
  [MimeType.JAVASCRIPT]: '.js JavaScript files',
  [MimeType.PDF]: '.pdf files',
  [MimeType.ZIP]: '.zip compressed files',
  [MimeType.SEVEN_ZIP]: '.7z compressed files',
  [MimeType.RAR]: '.rar compressed files',
  [MimeType.TAR]: '.tar archive files',
  [MimeType.GZIP]: '.gz compressed files',
  [MimeType.MS_WORD]: '.doc Microsoft Word files',
  [MimeType.MS_WORD_OPENXML]: '.docx Word files',
  [MimeType.MS_EXCEL]: '.xls Excel files',
  [MimeType.MS_EXCEL_OPENXML]: '.xlsx Excel files',
  [MimeType.MS_PPT]: '.ppt PowerPoint files',
  [MimeType.MS_PPT_OPENXML]: '.pptx PowerPoint files',
  [MimeType.FORM_URLENCODED]: 'Form URL-encoded data',
  [MimeType.OCTET_STREAM]: 'Binary data (generic)',

  [MimeType.TTF]: '.ttf font files',
  [MimeType.WOFF]: '.woff font files',
  [MimeType.WOFF2]: '.woff2 font files',
  [MimeType.EOT]: '.eot font files',

  [MimeType.MULTIPART_FORM_DATA]: 'Form data with file upload',
}
